FRTH_PRJCT_OF_DJANGO/FRTH_PRJCT_OF_DJANGO/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from frth_app import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^frth_app/', include("frth_app.urls")),
    url(r'^logout/', views.user_logout, name='logout'),
    url(r'^special/', views.special, name='special'),
]

FRTH_PRJCT_OF_DJANGO/frth_app/urls.py
from frth_app import views
from django.conf.urls import url

app_name = 'frth_app'

urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^login/', views.user_login, name='user_login'),
]

FRTH_PRJCT_OF_DJANGO/frth_app/models.py
from django.db import models
from  django.contrib.auth.models import User

# Create your models here.

class User_Profile(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #ADDING EXTRA ATTRIBUTES OTHER THE USER ALREADY HAS

    port_folio = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_pic',blank=True)

    def __str__(self):
        return self.user.username

FRTH_PRJCT_OF_DJANGO/frth_app/forms.py
from django import forms
from frth_app.models import User_Profile
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')

class User_ProfileForm(forms.ModelForm):
    class Meta():
        model = User_Profile
        fields = ('port_folio','picture')

FRTH_PRJCT_OF_DJANGO/frth_app/views.py
from django.shortcuts import render
from frth_app.forms import UserForm,User_ProfileForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth import authenticate,logout,login
from django.http import HttpResponseRedirect, HttpResponse

# Create your views here.

def index(req):
    return render(req,'frth_app/index.html')

@login_required
def special(req):
    return HttpResponse("You'r Logged In : Nice:) ")

@login_required
def user_logout(req):
    logout(req)
    return HttpResponseRedirect(reverse('index'))

def register(req):
     registered = False

     if req.method == "POST":
         user_form = UserForm(data=req.POST)
         profile_form = User_ProfileForm(data=req.POST)

         if user_form.is_valid() and profile_form.is_valid():
             user = user_form.save()
             user.set_password(user.password)
             user.save()

             profile = profile_form.save(commit=False)
             profile.user = user

             if 'profile_pic' in req.FILES:
                 profile.profile_pic = req.FILES('profile_pic')

             profile.save()

             registered=True
         else:
             print("EROOOORRRR")
     else:
         user_form = UserForm()
         profile_form = User_ProfileForm()

     return render(req,'frth_app/register.html',{'user_form':user_form,
                                                 'profile_form':profile_form,
                                                  'registered':registered,})

def user_login(req):
    if req.method == 'POST':
        username = req.POST.get('username')
        password = req.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(req,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                print("NOT AN ACTIVE ACCOUNT")
        else:
            print("INVALID LOGIN CREDENTIALS")
            print("WRONG DATA IS:")
            print("Username : {} Password : {}".format(username,password))
    else:
        return render(req,'frth_app/login.html',{})

FRTH_PRJCT_OF_DJANGO/templates/frth_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
      <div class="container">
        <ul class="navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'frth_app:register' %}">Register</a></li>

          {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li class="nav-item"><a class="nav-link" href="{% url 'frth_app:user_login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      <!-- #inside this nothing can be inherited -->
      {% endblock %}
    </div>
  </body>
</html>

FRTH_PRJCT_OF_DJANGO/templates/frth_app/index.html
{% extends "frth_app/base.html" %}
{% block body_block %}
<center>
  <h1>INDEX PAGE IS DISPLAYED</h1>
</center>
{% endblock %}

FRTH_PRJCT_OF_DJANGO/templates/frth_app/login.html
{% extends "frth_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>PLEASE LOGIN HERE</h1>
  <form action="{% url 'frth_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">UserName :</label>
    <input type="text" name="username" placeholder="Enter Username">
    <label for="password">Password :</label>
    <input type="password" name="password">
    <input type="submit" name="" value="Login">
  </form>
</div>
{% endblock %}

FRTH_PRJCT_OF_DJANGO/templates/frth_app/register.html
{% extends "frth_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <div class="container">
    {% if registered %}
    <h1>Thank You For Registering :)</h1>
    {% else %}
    <h1>REGISTER HERE!</h1><br>
    <h2>Fill Up The Form</h2><br>
    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" class="btn btn-primary" value="Register">
    </form>
    {% endif %}
  </div>
</div>

{% endblock %}